name : ci
on :
  push: 
     branches:
      - main
jobs:
   build :
     runs-on: ubuntu_latest
     steps :
         - name : checkout
           uses : checkout@v3
         - name : log in to docker
           uses : docker/login-acion@v2
           with :
              username : ${{secrets.DOCKER_USERNAME}}
              password : ${{secrets.DOCKER_TOKEN}}
         - name : Set up github buildx
           uses : docker/setup-buildx-action@v2
         - name : Build and Push
           uses : docker/build-push-action@v4
           with :
               context : .
               file : ./dockerfile
               push : True
               tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest


              
              
